### PR TITLE
Add $gonad

### PR DESCRIPTION
**Pull request by lordshisho**
Please do this really fast

ok thanks

love you

love,

shisho

and the rest of sei

### CODE REVIEW

**Comment by decoder-developer** [comment]
pls

**Comment by lordshisho** [comment]
pls

**Comment by ffilipovicc98** [comment]
Guys, can you make sure that only changes you do in token-list file are related only to your token. Please take a look at current diff.

**Comment by ffilipovicc98** [comment]
You did it in https://github.com/dragonswap-app/assets/pull/57

**Pull request closed without merging**
